services:
  web:
    build: .
    command: python manage.py migrate && python manage.py csu &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wallet_network
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: wallet_postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wallet_network


volumes:
  postgres_data:

networks:
  wallet_network:
    driver: bridge
