# Generated by Django 5.2.6 on 2025-10-02 06:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecentChangeWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "at_data",
                    models.DateTimeField(verbose_name="дата посленего изменения"),
                ),
                ("type_operation", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="UUID индификатор",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Баланc кошелька",
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Дата и время последнего обновления",
                    ),
                ),
                (
                    "at_create",
                    models.DateTimeField(
                        auto_now=True, verbose_name="дата создания кошелька"
                    ),
                ),
                (
                    "recent_charge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallet.recentchangewallet",
                        verbose_name="экзамепляр класса с описанием последнего изменения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кошелек",
                "verbose_name_plural": "Кошельки",
                "db_table": "wallets",
                "ordering": ["-time_update"],
            },
        ),
    ]
