# Generated by Django 5.2.6 on 2025-10-02 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="recent_charge",
        ),
        migrations.DeleteModel(
            name="RecentChangeWallet",
        ),
    ]
