# Generated by Django 5.2.6 on 2025-10-02 08:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_alter_wallet_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="UUID индификатор",
            ),
        ),
    ]
